version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: salesphere-redis
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - salesphere-network

networks:
  salesphere-network:
    driver: bridge
